//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfLocalization.Demo.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WpfLocalization.Demo.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Icon_Flag {
            get {
                object obj = ResourceManager.GetObject("Icon_Flag", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Image_Capital {
            get {
                object obj = ResourceManager.GetObject("Image_Capital", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth date.
        /// </summary>
        internal static string Label_BirthDate {
            get {
                return ResourceManager.GetString("Label_BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth date.
        /// </summary>
        internal static string Label_BirthDateInfo {
            get {
                return ResourceManager.GetString("Label_BirthDateInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capital.
        /// </summary>
        internal static string Label_Capital {
            get {
                return ResourceManager.GetString("Label_Capital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string Label_Country {
            get {
                return ResourceManager.GetString("Label_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current culture.
        /// </summary>
        internal static string Label_Culture {
            get {
                return ResourceManager.GetString("Label_Culture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        internal static string Label_Currency {
            get {
                return ResourceManager.GetString("Label_Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today is.
        /// </summary>
        internal static string Label_Date {
            get {
                return ResourceManager.GetString("Label_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flag.
        /// </summary>
        internal static string Label_Flag {
            get {
                return ResourceManager.GetString("Label_Flag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string Label_Information {
            get {
                return ResourceManager.GetString("Label_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input data.
        /// </summary>
        internal static string Label_InputData {
            get {
                return ResourceManager.GetString("Label_InputData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Label_Language {
            get {
                return ResourceManager.GetString("Label_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Label_Name {
            get {
                return ResourceManager.GetString("Label_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a number.
        /// </summary>
        internal static string Label_Styles_EnterNumber {
            get {
                return ResourceManager.GetString("Label_Styles_EnterNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current UI culture.
        /// </summary>
        internal static string Label_UICulture {
            get {
                return ResourceManager.GetString("Label_UICulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a localized non-dependency property..
        /// </summary>
        internal static string NonDepCustomControl_Message {
            get {
                return ResourceManager.GetString("NonDepCustomControl_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are born on {0:MMM dd}.
        /// </summary>
        internal static string Text_BirthDateInfo {
            get {
                return ResourceManager.GetString("Text_BirthDateInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are {0} days left until your next birthday!.
        /// </summary>
        internal static string Text_BirthDateInfo_2 {
            get {
                return ResourceManager.GetString("Text_BirthDateInfo_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Washington, D.C..
        /// </summary>
        internal static string Text_Capital {
            get {
                return ResourceManager.GetString("Text_Capital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to United States.
        /// </summary>
        internal static string Text_Country {
            get {
                return ResourceManager.GetString("Text_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can use the LocalizationScope.Culture and LocalizationScope.UICulture attached properties anywhere in the application to set the language and/pr the formatting culture of an element and its child elements. Use the combo-boxes below to change the settings for the content of this tab only..
        /// </summary>
        internal static string Text_MultipleLanguages {
            get {
                return ResourceManager.GetString("Text_MultipleLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can use the extension in style setters including data triggers..
        /// </summary>
        internal static string Text_Styles {
            get {
                return ResourceManager.GetString("Text_Styles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have entered a negative number..
        /// </summary>
        internal static string Text_Styles_Number_Negative {
            get {
                return ResourceManager.GetString("Text_Styles_Number_Negative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have entered a positive number..
        /// </summary>
        internal static string Text_Styles_Number_Positive {
            get {
                return ResourceManager.GetString("Text_Styles_Number_Positive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have entered zero..
        /// </summary>
        internal static string Text_Styles_Number_Zero {
            get {
                return ResourceManager.GetString("Text_Styles_Number_Zero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello {0} {1} and welcome to Washington, D.C. Below you can find information about this country and formatting styles..
        /// </summary>
        internal static string Text_Welcome {
            get {
                return ResourceManager.GetString("Text_Welcome", resourceCulture);
            }
        }
    }
}
